[listener]
type="socket"

[service.ftp]
type="ftp"

[[port]]
port="tcp/21"
services=["ftp"]

[service.ssh]
type="ssh-simulator"

[[port]]
port="tcp/22"
services=["ssh"]

[service.smtp]
type="smtp"

[[port]]
port="tcp/25"
services=["smtp"]

[service.ethereum]
type="ethereum"

[[port]]
port="tcp/8545"
services=["ethereum"]

[channel.file]
type="file"
filename="logs/honeytrap.log"

[[filter]]
channel=["file"]

[[logging]]
output="stdout"
level="debug"