[listener]
type="socket"

[service.ssh]
type="ssh-simulator"

[[port]]
port="tcp/22"
services=["ssh"]

[service.smtp]
type="smtp"

[[port]]
port="tcp/25"
services=["smtp"]

[channel.file]
type="file"
filename="logs/honeytrap.log"

[[filter]]
channel=["file"]

[[logging]]
output="stdout"
level="debug"